import '../Models/restaurants.dart';
import '../Models/food_review_model.dart';
import '../Models/message_model.dart';
import '../Models/table_model.dart';

List<Restaurant> mockRestaurants = [
  Restaurant(
    id: 'r1',
    name: 'Pasta Corner',
    description: 'A cozy place for authentic Italian pasta dishes.',
    imagePath: 'assets/images/restaurant.png',
    rating: 5.0,
    reviewCount: 120,
    tags: ['Pasta', 'Italian'],
    deliveryTime: '15-30 min',
    priceLevel: '\$\$\$',
    freeDelivery: false,
    address: '123 Pasta St, Foodville',
    phoneNumber: '123-456-7890',
    isOpen: true,
    operatingHours: {
      'Monday': '8am-10pm',
      'Tuesday': '8am-10pm',
      'Wednesday': '8am-10pm',
      'Thursday': '8am-10pm',
      'Friday': '8am-11pm',
      'Saturday': '9am-11pm',
      'Sunday': 'Closed',
    },
    location: {'lat': 12.34, 'lng': 56.78},
    discounts: ['Up to 60% off', '70% off: abapay'],
    menu: [
      MenuItem(
        id: 'm1',
        name: 'Spaghetti Carbonara',
        description: 'Classic Italian pasta with creamy sauce and pancetta.',
        imageUrl: 'assets/images/asianfood.png',
        price: 6.99,
        originalPrice: 9.99,
        category: 'popular',
        restaurantId: 'r1',
        restaurantName: 'Pasta Corner',
        customizations: [
          CustomizationOption(name: 'Cheese', choices: ['Parmesan', 'None']),
          CustomizationOption(
              name: 'Spice Level', choices: ['Mild', 'Medium', 'Hot']),
        ],
        reviews: [
          Review(
              reviewer: 'Alice',
              rating: 4.5,
              comment: 'Delicious! Just like in Rome.'),
          Review(
              reviewer: 'Bob', rating: 4.0, comment: 'Creamy and satisfying.'),
        ],
      ),
      MenuItem(
        id: 'm2',
        name: 'Classic Lasagna',
        description: 'Layers of pasta, meat, and cheese baked to perfection.',
        imageUrl: 'assets/images/asianfood.png',
        price: 7.50,
        category: 'popular',
        restaurantId: 'r1',
        restaurantName: 'Pasta Corner',
        customizations: [],
        reviews: [
          Review(reviewer: 'El', rating: 4.5, comment: 'Delicious!'),
          Review(reviewer: 'Haha', rating: 4.0, comment: 'Satisfying.'),
        ],
      ),
      MenuItem(
        id: 'm3',
        name: 'Cola',
        description: 'Refreshing cola to complement your meal.',
        imageUrl: 'assets/images/asianfood.png',
        price: 2.50,
        category: 'popular',
        restaurantId: 'r1',
        restaurantName: 'Pasta Corner',
        customizations: [],
        reviews: [
          Review(reviewer: 'Jack', rating: 4.0, comment: 'Nice and cold.'),
          Review(reviewer: 'Jayb', rating: 5.0, comment: 'Perfect drink.'),
        ],
      ),
    ],
    isDeliveryOnly: false,
    totalSeats: 50,
    availableSeats: 20,
    chatHistory: [
      ChatMessage(
        text: "Are your noodles spicy?",
        isUser: true,
        time: DateTime.now().subtract(Duration(minutes: 20)),
      ),
      ChatMessage(
        text: "Yes, we have mild, medium, and hot spice levels.",
        isUser: false,
        time: DateTime.now().subtract(Duration(minutes: 18)),
      ),
    ],
    tables: [
      TableModel(
        id: 1,
        tableNumber: "1",
        seats: 4,
        isBooked: false,
        isAvailable: true,
        locationType: "Indoor",
        features: ["Pet-friendly"],
        minSpend: 20.0,
        reservationTimeSlots: ["12:00 PM", "2:00 PM", "6:00 PM"],
      ),
      TableModel(
        id: 2,
        tableNumber: "2",
        seats: 2,
        isBooked: true,
        isAvailable: false,
        locationType: "Outdoor",
        features: ["Smoking area"],
      ),
    ],
  )
];

  // -- Restaurant 2 --
//   Restaurant(
//     id: 'r2',
//     name: "Cheap Charlie's (TTP)",
//     description: 'Affordable Western food for everyday cravings.',
//     imagePath: 'assets/images/restaurant.png',
//     rating: 5.0,
//     reviewCount: 80,
//     tags: ['Western', 'Burger'],
//     deliveryTime: '35-65 min',
//     priceLevel: '\$\$',
//     freeDelivery: false,
//     address: '456 Cheap St, Budgettown',
//     phoneNumber: '987-654-3210',
//     isOpen: true,
//     operatingHours: {
//       'Monday': '9am-9pm',
//       'Tuesday': '9am-9pm',
//       'Wednesday': '9am-9pm',
//       'Thursday': '9am-9pm',
//       'Friday': '9am-10pm',
//       'Saturday': '10am-10pm',
//       'Sunday': 'Closed',
//     },
//     location: {'lat': 21.43, 'lng': 65.87},
//     discounts: ['Up to 50% off'],
//     menu: [
//       MenuItem(
//         id: 'm4',
//         name: 'Beef Burger',
//         description: 'Juicy beef patty with fresh lettuce and tomato.',
//         imageUrl: 'assets/images/asianfood.png',
//         price: 4.00,
//         originalPrice: 6.50,
//         category: 'popular',
//         restaurantId: 'r2',
//         restaurantName: "Cheap Charlie's (TTP)",
//         customizations: [],
//         reviews: [
//           Review(
//               reviewer: 'Alice', rating: 4.5, comment: 'Juicy and delicious.'),
//           Review(reviewer: 'Bob', rating: 4.0, comment: 'Good taste.'),
//         ],
//       ),
//       MenuItem(
//         id: 'm5',
//         name: 'Fish & Chips',
//         description: 'Crispy fish fillet served with golden fries.',
//         imageUrl: 'assets/images/asianfood.png',
//         price: 5.25,
//         category: 'popular',
//         restaurantId: 'r2',
//         restaurantName: "Cheap Charlie's (TTP)",
//         customizations: [],
//         reviews: [
//           Review(reviewer: 'Alice', rating: 4.5, comment: 'Perfect crunch.'),
//           Review(reviewer: 'Bob', rating: 4.0, comment: 'Loved it.'),
//         ],
//       ),
//     ],
//     isDeliveryOnly: false,
//     totalSeats: 40,
//     availableSeats: 15,
//     chatHistory: [
//       ChatMessage(
//         text: "Are your noodles spicy?",
//         isUser: true,
//         time: DateTime.now().subtract(Duration(minutes: 20)),
//       ),
//       ChatMessage(
//         text: "Yes, we have mild, medium, and hot spice levels.",
//         isUser: false,
//         time: DateTime.now().subtract(Duration(minutes: 18)),
//       ),
//     ],
//   ),

//   // -- Restaurant 3 --
//   Restaurant(
//     id: 'r3',
//     name: "Sushi World",
//     description: 'Fresh sushi and Japanese delicacies.',
//     imagePath: 'assets/images/restaurant.png',
//     rating: 4.7,
//     reviewCount: 200,
//     tags: ['Sushi', 'Japanese'],
//     deliveryTime: '25-40 min',
//     priceLevel: '\$\$\$\$',
//     freeDelivery: true,
//     address: '789 Sushi Rd, Fish City',
//     phoneNumber: '555-123-4567',
//     isOpen: true,
//     operatingHours: {
//       'Monday': '11am-10pm',
//       'Tuesday': '11am-10pm',
//       'Wednesday': '11am-10pm',
//       'Thursday': '11am-10pm',
//       'Friday': '11am-11pm',
//       'Saturday': '12pm-11pm',
//       'Sunday': 'Closed',
//     },
//     location: {'lat': 34.56, 'lng': 78.90},
//     discounts: ['30% off first order', 'Buy 1 Get 1 Free'],
//     menu: [
//       MenuItem(
//         id: 'm6',
//         name: 'Salmon Sushi Set',
//         description: 'Fresh salmon sushi with avocado and cucumber.',
//         imageUrl: 'assets/images/asianfood.png',
//         price: 12.00,
//         originalPrice: 15.00,
//         category: 'discount',
//         restaurantId: 'r3',
//         restaurantName: 'Sushi World',
//         customizations: [],
//         reviews: [
//           Review(reviewer: 'Alice', rating: 4.5, comment: 'Fresh and tasty.'),
//           Review(reviewer: 'Bob', rating: 4.0, comment: 'Very good.'),
//         ],
//       ),
//       MenuItem(
//         id: 'm7',
//         name: 'Maki Roll Platter',
//         description: 'Assorted maki rolls with crab, avocado, and cucumber.',
//         imageUrl: 'assets/images/asianfood.png',
//         price: 10.50,
//         category: 'popular',
//         restaurantId: 'r3',
//         restaurantName: 'Sushi World',
//         customizations: [],
//         reviews: [
//           Review(reviewer: 'Alice', rating: 4.5, comment: 'Excellent variety.'),
//           Review(reviewer: 'Bob', rating: 4.0, comment: 'Loved the rolls.'),
//         ],
//       ),
//     ],
//     isDeliveryOnly: false,
//     totalSeats: 60,
//     availableSeats: 40,
//     chatHistory: [
//       ChatMessage(
//         text: "Can I pre-order sushi for 7pm?",
//         isUser: true,
//         time: DateTime.now().subtract(Duration(minutes: 30)),
//       ),
//       ChatMessage(
//         text: "Sure, we’ll have it ready for you at 7pm.",
//         isUser: false,
//         time: DateTime.now().subtract(Duration(minutes: 25)),
//       ),
//     ],
//   ),

//   // -- Restaurant 4 --
//   Restaurant(
//     id: 'r4',
//     name: "Noodle Express",
//     description: 'Quick and tasty Asian noodle dishes.',
//     imagePath: 'assets/images/restaurant.png',
//     rating: 4.5,
//     reviewCount: 90,
//     tags: ['Asian', 'Noodles'],
//     deliveryTime: '10-20 min',
//     priceLevel: '\$',
//     freeDelivery: true,
//     address: '321 Noodle Ave, Flavor Town',
//     phoneNumber: '444-555-6666',
//     isOpen: true,
//     operatingHours: {
//       'Monday': '7am-9pm',
//       'Tuesday': '7am-9pm',
//       'Wednesday': '7am-9pm',
//       'Thursday': '7am-9pm',
//       'Friday': '7am-10pm',
//       'Saturday': '8am-10pm',
//       'Sunday': 'Closed',
//     },
//     location: {'lat': 45.67, 'lng': 89.01},
//     discounts: ['30% off first order'],
//     menu: [
//       MenuItem(
//         id: 'm8',
//         name: 'Chicken Noodles',
//         description: 'Stir-fried noodles with chicken and vegetables.',
//         imageUrl: 'assets/images/asianfood.png',
//         price: 3.50,
//         category: 'popular',
//         restaurantId: 'r4',
//         restaurantName: 'Noodle Express',
//         customizations: [],
//         reviews: [
//           Review(reviewer: 'Alice', rating: 4.5, comment: 'Very tasty!'),
//           Review(reviewer: 'Bob', rating: 4.0, comment: 'Good portion size.'),
//         ],
//       ),
//       MenuItem(
//         id: 'm9',
//         name: 'Spicy Ramen Bowl',
//         description:
//             'Spicy ramen with tender pork, soft-boiled egg, and veggies.',
//         imageUrl: 'assets/images/asianfood.png',
//         price: 5.00,
//         category: 'discount',
//         restaurantId: 'r4',
//         restaurantName: 'Noodle Express',
//         customizations: [],
//         reviews: [
//           Review(
//               reviewer: 'Alice', rating: 4.5, comment: 'Spicy and flavorful!'),
//           Review(reviewer: 'Bob', rating: 4.0, comment: 'Great taste.'),
//         ],
//       ),
//     ],
//     isDeliveryOnly: false,
//     totalSeats: 30,
//     availableSeats: 10,
//     chatHistory: [
//       ChatMessage(
//         text: "Are your noodles spicy?",
//         isUser: true,
//         time: DateTime.now().subtract(Duration(minutes: 20)),
//       ),
//       ChatMessage(
//         text: "Yes, we have mild, medium, and hot spice levels.",
//         isUser: false,
//         time: DateTime.now().subtract(Duration(minutes: 18)),
//       ),
//     ],
//   ),
// ];
